<?php

/**
 * @file
 * Contains tfs_mailchimp.module..
 */
use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\User;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function tfs_mailchimp_form_mailchimp_signup_subscribe_block_tfs_signup_form_alter(&$form, FormStateInterface $form_state) {
  $form['#cache']['contexts'][0] = 'user';

  // Move title field to the top
  $form['mergevars']['TITLE']['#weight'] = 0;
  $form['mergevars']['EMAIL']['#weight'] = 50;

  // Prefill the form with some default values
  $user = Drupal::currentUser();
  if ($user->isAuthenticated()) {
    $user = User::load($user->id());
    
    if (!$user->get('field_user_subscribed')->value) {
      $form['mergevars']['TITLE']['#default_value'] = $user->get('field_title')->value;
      $form['mergevars']['EMAIL']['#default_value'] = $user->getEmail();
      $form['mergevars']['FNAME']['#default_value'] = $user->get('field_firstname')->value;
      $form['mergevars']['LNAME']['#default_value'] = $user->get('field_lastname')->value;
    }
    else {
      $form['#access'] = FALSE;
    }
  }

  $form['#submit'][] = 'tfs_mailchimp_signup_submit';
}

/**
 * Custom submit handler for mailchimp signup
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function tfs_mailchimp_signup_submit($form, FormStateInterface $form_state) {
  $user = Drupal::currentUser();
  if ($user->isAuthenticated()) {
    $user = User::load($user->id());
    $user
      ->set('field_user_subscribed', 1)
      ->save();
  }
}